// This file is auto-generated by @hey-api/openapi-ts

export type ExpositorSchema = {
    id: string;
    nome: string;
    descricao?: string;
    imagem_perfil?: string;
    instagram?: string;
    facebook?: string;
    tiktok?: string;
    criado_em: string;
    atualizado_em: string;
};

export type CreateExpositorSchema = {
    nome: string;
    descricao?: string;
    imagem_perfil?: string;
    instagram?: string;
    facebook?: string;
    tiktok?: string;
};

export type PecaSchema = {
    id: string;
    nome: string;
    preco: number;
    imagem?: string;
    expositor: string;
    criado_em: string;
    atualizado_em: string;
};

export type CreatePecaSchema = {
    nome: string;
    preco: number;
    imagem?: string;
    expositor: string;
};

export type ListarExpositoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/expositores';
};

export type ListarExpositoresResponses = {
    /**
     * OK
     */
    200: Array<ExpositorSchema>;
};

export type ListarExpositoresResponse = ListarExpositoresResponses[keyof ListarExpositoresResponses];

export type CriarExpositorData = {
    body: CreateExpositorSchema;
    path?: never;
    query?: never;
    url: '/api/expositores';
};

export type CriarExpositorResponses = {
    /**
     * OK
     */
    200: ExpositorSchema;
};

export type CriarExpositorResponse = CriarExpositorResponses[keyof CriarExpositorResponses];

export type DeletarExpositorData = {
    body?: never;
    path: {
        expositor_id: string;
    };
    query?: never;
    url: '/api/expositores/{expositor_id}';
};

export type DeletarExpositorResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletarExpositorResponse = DeletarExpositorResponses[keyof DeletarExpositorResponses];

export type ObterExpositorData = {
    body?: never;
    path: {
        expositor_id: string;
    };
    query?: never;
    url: '/api/expositores/{expositor_id}';
};

export type ObterExpositorResponses = {
    /**
     * OK
     */
    200: ExpositorSchema;
};

export type ObterExpositorResponse = ObterExpositorResponses[keyof ObterExpositorResponses];

export type AtualizarExpositorData = {
    body: CreateExpositorSchema;
    path: {
        expositor_id: string;
    };
    query?: never;
    url: '/api/expositores/{expositor_id}';
};

export type AtualizarExpositorResponses = {
    /**
     * OK
     */
    200: ExpositorSchema;
};

export type AtualizarExpositorResponse = AtualizarExpositorResponses[keyof AtualizarExpositorResponses];

export type ListarPecasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pecas';
};

export type ListarPecasResponses = {
    /**
     * OK
     */
    200: Array<PecaSchema>;
};

export type ListarPecasResponse = ListarPecasResponses[keyof ListarPecasResponses];

export type CriarPecaData = {
    body: CreatePecaSchema;
    path?: never;
    query?: never;
    url: '/api/pecas';
};

export type CriarPecaResponses = {
    /**
     * OK
     */
    200: PecaSchema;
};

export type CriarPecaResponse = CriarPecaResponses[keyof CriarPecaResponses];

export type DeletarPecaData = {
    body?: never;
    path: {
        peca_id: string;
    };
    query?: never;
    url: '/api/pecas/{peca_id}';
};

export type DeletarPecaResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletarPecaResponse = DeletarPecaResponses[keyof DeletarPecaResponses];

export type ObterPecaData = {
    body?: never;
    path: {
        peca_id: string;
    };
    query?: never;
    url: '/api/pecas/{peca_id}';
};

export type ObterPecaResponses = {
    /**
     * OK
     */
    200: PecaSchema;
};

export type ObterPecaResponse = ObterPecaResponses[keyof ObterPecaResponses];

export type AtualizarPecaData = {
    body: CreatePecaSchema;
    path: {
        peca_id: string;
    };
    query?: never;
    url: '/api/pecas/{peca_id}';
};

export type AtualizarPecaResponses = {
    /**
     * OK
     */
    200: PecaSchema;
};

export type AtualizarPecaResponse = AtualizarPecaResponses[keyof AtualizarPecaResponses];

export type ClientOptions = {
    baseUrl: string;
};