# Generated by Django 5.2 on 2025-04-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
